platform :ios, '9.0'
use_frameworks!

target 'AssetChecker_Example' do
  pod 'AssetChecker', :path => '../'

  target 'AssetChecker_Tests' do
    inherit! :search_paths

    
  end
end

#Post installation hook to symlink the directory into PODS_ROOT to simulate how it will work when downloaded. 
post_install do |installer|
    require 'fileutils'
    
    FileUtils.rm_rf('Pods/AssetChecker')
    FileUtils.mkdir('Pods/AssetChecker')
    FileUtils.ln_s('../../../Classes', 'Pods/AssetChecker/Classes')
    FileUtils.ln_s('../../../run', 'Pods/AssetChecker/run')
end
